branch-defaults:
  dev-linhchi-new:
    environment: hack-mates
    group_suffix: null
global:
  application_name: hack_mates
  default_ec2_keyname: hackmates-key
  default_platform: Python 2.7
  default_region: us-east-1
  profile: eb-cli
  sc: git
