# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='hackathon_image',
            field=models.ImageField(blank=True, default=b'images/users/default/default.png', upload_to=b''),
        ),
    ]
