# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20160717_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='length',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default=b'HackerPack Land', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='platform_choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'ANDROID', b'Android'), (b'IOS', b'iOS'), (b'WEB', b'Web Development'), (b'HARDWARE', b'Hardware')], max_length=24),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='school',
            field=models.CharField(blank=True, default=b'HackerPack', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='studies',
            field=models.CharField(blank=True, default=b'Hacking', max_length=32),
        ),
    ]
