# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_auto_20160718_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='platform_choices',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(b'Android', b'Android'), (b'iOS', b'iOS'), (b'Web Development', b'Web Development'), (b'Hardware', b'Hardware')], max_length=36),
        ),
    ]
