# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 19:32
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20160719_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preference_tags',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='platform_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(b'Android', b'Android'), (b'iOS', b'iOS'), (b'Web Development', b'Web Development'), (b'Hardware', b'Hardware')], max_length=36),
        ),
    ]
