# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20160722_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=b'None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default=b'None', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='platform_choices',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='frameworks',
            field=models.TextField(blank=True, default=b'None', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ideas',
            field=models.TextField(blank=True, default=b'None yet :(', help_text=b'Tell us your hackathon ideas!', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='about',
            field=models.TextField(blank=True, default=b'I am a hackmate!', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='src.UserLanguage'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='src.UserRoles'),
        ),
    ]
