# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20160731_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default=b'images/users/default/default.png', upload_to=b''),
        ),
    ]
